[package]
name = "fbhash"
version = "0.1.0"
authors = ["Erwin van Eijk <235739+erwinvaneijk@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/erwinvaneijk/fbhash"
description = "A Similarity Hashing Scheme for Digital Forensics"
readme = "README.md"
categories = ["command-line-utilities", "digital forensics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fbhash_indexer"
path = "src/indexer.rs"

[[bin]]
name = "fbhash_query"
path = "src/query.rs"

[profile.release]
lto = true
overflow-checks = true
panic = "abort"

[dependencies]
env_logger = "0.8.3"
itertools = "0.10.0"
frequency = "^1.0.0"
frequency-hashmap = "^1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
ordered-float = "2.0"
priority-queue = "1.1.1"
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hash_hasher = "2.0"

[dev-dependencies]
pretty_assertions = "0.7.1"
float-cmp = "0.8.0"
serde_test = "1.0"
